Negative investor signup flows and successful deal purchase flow adde…
kulkarnikarthik/kredx-test-infra pull request #4
Opened 2017-06-09 18:03 UTC by kulkarnikarthik

…d, along with minor changes to method names

2017-06-10 16:42 UTC, njchandu requested changes

2017-06-10 16:42 UTC, njchandu commented on src/test/java/base/BasePage.java
> +        String alphaNumerics = "qwertyuiopasdfghjklzxcvbnm1234567890";
Read this from data.yml

2017-06-10 16:42 UTC, njchandu commented on src/test/java/base/BasePage.java
>          String alphaNumerics = "qwertyuiopasdfghjklzxcvbnm";
This too.

2017-06-10 16:42 UTC, njchandu commented on src/test/java/models/ui/TestData.java
> +    public String getincorrectPasswordErrorMessage() {
*getIncorrectPasswordErrorMessage

2017-06-10 16:42 UTC, njchandu commented on src/test/java/models/ui/TestData.java
>          return inCorrectPasswordErrorMessage;
*incorrect

2017-06-10 16:42 UTC, njchandu commented on src/test/java/pages/AgreementSummaryPage.java
> +//        try {
Remove commented code

2017-06-10 16:42 UTC, njchandu commented on src/test/java/pages/AgreementSummaryPage.java
> +        WebDriverWait wait = new WebDriverWait(driver, 5000);
Read the timeout from config.yml

2017-06-10 16:42 UTC, njchandu commented on src/test/java/pages/AgreementSummaryPage.java
> +        WebDriverWait wait = new WebDriverWait(driver, 10000);
Read the timeout from config.yml

2017-06-10 16:42 UTC, njchandu commented on src/test/java/pages/CurrentDealsPage.java
> +    @FindBy(xpath = "//div[div[div[a[@href='/financier/dashboard/deals/DEZ08LWKMN']]]]/div[3]/div/div[2]/div/div/div/input")
See if you can avoid the usage of DEZ08LWKMN

2017-06-10 16:42 UTC, njchandu commented on src/test/java/pages/CurrentDealsPage.java
> +    @FindBy(xpath = "//div[div[div[div[a[@href='/financier/dashboard/deals/DEZ08LWKMN']]]]]//div[3]/div/div[2]/div[2]/div/button")
Same here

2017-06-10 16:42 UTC, njchandu commented on src/test/java/pages/CurrentDealsPage.java
> +    @FindBy(xpath = "//a[@href = '/financier/dashboard/deals/DEZ08LWKMN']/button")
Here too

2017-06-10 16:42 UTC, njchandu commented on src/test/java/pages/CurrentDealsPage.java
> +        WebDriverWait wait = new WebDriverWait(driver, 5000);
Read the timeout from config.yml

2017-06-10 16:42 UTC, njchandu commented on src/test/java/pages/CurrentDealsPage.java
> +    public String successfulDealConfirmation(){
name the method better, getConfirmationMessage() or something like that.

2017-06-10 16:42 UTC, njchandu commented on src/test/java/pages/DealInterstitialOverlayPage.java
> +        WebDriverWait wait = new WebDriverWait(driver, 5000);
Read the timeout from config.yml

2017-06-10 16:42 UTC, njchandu commented on src/test/java/pages/DealInterstitialOverlayPage.java
> +        WebDriverWait wait = new WebDriverWait(driver, 5000);
I notice you have used it at multiple places, you could add this to BasePage.java and reuse it in all the pages.

2017-06-10 16:42 UTC, njchandu commented on src/test/java/pages/FinancierSignUpPage.java
> +        WebDriverWait wait = new WebDriverWait(driver, 10000);
here too

2017-06-10 16:42 UTC, njchandu commented on src/test/java/pages/PaymentsPage.java
> +    @FindBy(id = "payBtn1")
good change 👍

2017-06-10 16:42 UTC, njchandu commented on src/test/java/tests/BuyDealsTest.java
> +        driver.manage().timeouts().implicitlyWait(config.getTimeout(), TimeUnit.SECONDS);
This should ideally be present in BaseTest unless you need a specific timeout for this Test

2017-06-10 16:42 UTC, njchandu commented on src/test/java/tests/InvestorSignUpTest.java
> +}
👍 very neatly written tests

2017-06-10 16:42 UTC, njchandu commented on src/test/java/tests/LoginFlowTest.java
> +        Assert.assertEquals(loginPage.isIncorrectPasswordErrorMessageVisible(),data.getincorrectPasswordErrorMessage());
*getIncorrectPasswordErrorMessage
You can use Shift+F6 to rename and refactor the variables/methods.

2017-06-10 16:42 UTC, njchandu commented on src/test/resources/test-suite/regression-test-suite.xml
>  <suite name="Create Flow">
Rename to Regression

2017-06-11 07:11 UTC, kulkarnikarthik commented on src/test/java/pages/CurrentDealsPage.java
> +    @FindBy(xpath = "//div[div[div[a[@href='/financier/dashboard/deals/DEZ08LWKMN']]]]/div[3]/div/div[2]/div/div/div/input")
its the deal identifier, the only thing that was unique to traverse from, to arrive at amount & buy now button

2017-06-11 07:11 UTC, kulkarnikarthik commented on src/test/java/pages/CurrentDealsPage.java
> +    @FindBy(xpath = "//div[div[div[div[a[@href='/financier/dashboard/deals/DEZ08LWKMN']]]]]//div[3]/div/div[2]/div[2]/div/button")
its the deal identifier, the only thing that was unique to traverse from, to arrive at amount & buy now button

2017-06-11 07:11 UTC, kulkarnikarthik commented on src/test/java/pages/CurrentDealsPage.java
> +    @FindBy(xpath = "//a[@href = '/financier/dashboard/deals/DEZ08LWKMN']/button")
its the deal identifier, the only thing that was unique to traverse from, to arrive at amount & buy now button

2017-06-11 07:15 UTC, kulkarnikarthik commented on src/test/resources/test-suite/regression-test-suite.xml
>  <suite name="Create Flow">
done

2017-06-11 07:16 UTC, kulkarnikarthik commented on src/test/java/tests/LoginFlowTest.java
> +        Assert.assertEquals(loginPage.isIncorrectPasswordErrorMessageVisible(),data.getincorrectPasswordErrorMessage());
done

2017-06-11 07:16 UTC, kulkarnikarthik commented on src/test/java/tests/InvestorSignUpTest.java
> +}
thanks

2017-06-11 07:19 UTC, kulkarnikarthik commented on src/test/java/tests/BuyDealsTest.java
> +        driver.manage().timeouts().implicitlyWait(config.getTimeout(), TimeUnit.SECONDS);
done, removed implicit wait from test

2017-06-11 07:20 UTC, kulkarnikarthik commented on src/test/java/pages/FinancierSignUpPage.java
> +        WebDriverWait wait = new WebDriverWait(driver, 10000);
will add this in next iteration

2017-06-11 07:20 UTC, kulkarnikarthik commented on src/test/java/pages/DealInterstitialOverlayPage.java
> +        WebDriverWait wait = new WebDriverWait(driver, 5000);
will add this in next iteration

2017-06-11 07:22 UTC, kulkarnikarthik commented on src/test/java/pages/CurrentDealsPage.java
> +    public String successfulDealConfirmation(){
done

2017-06-11 07:22 UTC, kulkarnikarthik commented on src/test/java/pages/CurrentDealsPage.java
> +        WebDriverWait wait = new WebDriverWait(driver, 5000);
will add this in next iteration

2017-06-11 07:27 UTC, kulkarnikarthik commented on src/test/java/models/ui/TestData.java
> +    public String getincorrectPasswordErrorMessage() {
done

2017-06-11 07:31 UTC, kulkarnikarthik commented on src/test/java/models/ui/TestData.java
>          return inCorrectPasswordErrorMessage;
done

2017-06-11 07:38 UTC, kulkarnikarthik commented on src/test/java/base/BasePage.java
>          String alphaNumerics = "qwertyuiopasdfghjklzxcvbnm";
done

2017-06-11 07:38 UTC, kulkarnikarthik commented on src/test/java/base/BasePage.java
> +        String alphaNumerics = "qwertyuiopasdfghjklzxcvbnm1234567890";
done

2017-06-11 07:40 UTC, njchandu commented on src/test/java/pages/CurrentDealsPage.java
> +    @FindBy(xpath = "//div[div[div[a[@href='/financier/dashboard/deals/DEZ08LWKMN']]]]/div[3]/div/div[2]/div/div/div/input")
wild guess, try this:
` +    @FindBy(xpath = "//div[div[div[a[@href='/financier/dashboard/deals/DEZ08LWKMN']]]]//input") `

// traverses multiple levels

2017-06-16 19:19 UTC, njchandu requested changes

2017-06-16 19:19 UTC, njchandu commented on src/test/java/base/BasePage.java
> +    protected TestData data;
make this static and see if you can think of why you may need to make it static

2017-06-16 19:19 UTC, njchandu commented on src/test/java/pages/CurrentDealsPage.java
> +    @FindBy(xpath = "//div[div[div[div[h5[contains(text(),'Sv Industries 2')]]]]]/div[3]/div/div[2]/div/div/div/input")
could you try with just //h5[contains(text(),'Sv Industries 2')]

2017-06-16 19:19 UTC, njchandu commented on src/test/java/pages/CurrentDealsPage.java
> +        WebDriverWait wait = new WebDriverWait(driver, 10000);
read the timeout from config.

2017-06-16 19:19 UTC, njchandu commented on src/test/java/pages/LoginPage.java
>          WebDriverWait wait = new WebDriverWait(driver,4000);
4 seconds can be very less on a moderately slow network

2017-06-16 19:19 UTC, njchandu commented on src/test/java/pages/LoginPage.java
>          WebDriverWait wait = new WebDriverWait(driver,4000);
preferably keep all the waits constant. preferably at the upper bound because these waits don't wait if the condition passes. It keeps polling every 500 ms for 4000 ms in this case.

2017-06-16 19:19 UTC, njchandu commented on src/test/java/pages/ManageFundsPage.java
> +    @FindBy(xpath = ".//div[contains(text(),'Please enter a valid amount for netbanking transactions')]")
you don't need a . before //div

2017-06-18 07:12 UTC, closed without merging